# -*- coding: utf-8 -*-
"""fixed_sod_homework_colab_with_toggle-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yvwNnn7gk5jen-0q2l0771zK7oaDcqSB
"""

# 1. Mount Google Drive and imports

from google.colab import drive
drive.mount('/content/drive')

import os
import time
import random
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger

from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, jaccard_score

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

# 2. Configuration + training size toggle

class CFG:
    DATA_ROOT = "/content/drive/MyDrive/ecssd"

    IMG_DIR = f"{DATA_ROOT}/images (1)"
    MASK_DIR = f"{DATA_ROOT}/ground_truth_mask"

    IMG_SIZE = 128
    BATCH_SIZE = 8
    EPOCHS = 15
    SEED = 42

    MODEL_DIR = "/content/models"
    LOG_DIR = "/content/logs"


FAST_MODE = False

if FAST_MODE:
    MAX_TOTAL_IMAGES = 300
else:
    MAX_TOTAL_IMAGES = None


print("FAST_MODE:", FAST_MODE)
print("MAX_TOTAL_IMAGES:", MAX_TOTAL_IMAGES)

os.makedirs(CFG.MODEL_DIR, exist_ok=True)
os.makedirs(CFG.LOG_DIR, exist_ok=True)

random.seed(CFG.SEED)
np.random.seed(CFG.SEED)
tf.random.set_seed(CFG.SEED)

# 3. Pair images with masks

def collect_pairs(image_dir, mask_dir):
    image_dir = Path(image_dir)
    mask_dir = Path(mask_dir)

    print("Image folder exists:", image_dir.exists())
    print("Mask folder exists:", mask_dir.exists())

    image_paths = sorted(
        list(image_dir.glob("*.jpg")) +
        list(image_dir.glob("*.jpeg")) +
        list(image_dir.glob("*.png"))
    )

    print("Images found:", len(image_paths))

    pairs = []

    for img_path in image_paths:
        possible_masks = [
            mask_dir / f"{img_path.stem}.png",
            mask_dir / f"{img_path.stem}.jpg",
            mask_dir / f"{img_path.stem}.jpeg",
        ]

        for mask_path in possible_masks:
            if mask_path.exists():
                pairs.append((str(img_path), str(mask_path)))
                break

    return pairs


all_pairs = collect_pairs(CFG.IMG_DIR, CFG.MASK_DIR)

random.seed(CFG.SEED)
random.shuffle(all_pairs)

if MAX_TOTAL_IMAGES is not None:
    all_pairs = all_pairs[:MAX_TOTAL_IMAGES]

print("Total image/mask pairs used:", len(all_pairs))
print("Example pair:", all_pairs[0] if all_pairs else "No data found")

# 4. Proper 70% train / 15% validation / 15% test split

train_pairs, temp_pairs = train_test_split(
    all_pairs,
    test_size=0.30,
    random_state=CFG.SEED,
    shuffle=True
)

val_pairs, test_pairs = train_test_split(
    temp_pairs,
    test_size=0.50,
    random_state=CFG.SEED,
    shuffle=True
)

total = len(all_pairs)

print("Train:", len(train_pairs), f"({len(train_pairs) / total:.1%})")
print("Validation:", len(val_pairs), f"({len(val_pairs) / total:.1%})")
print("Test:", len(test_pairs), f"({len(test_pairs) / total:.1%})")

# 5. Preprocessing: resize + normalize images and masks to [0, 1]

def load_image_and_mask(img_path, mask_path):
    img = tf.io.read_file(img_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, (CFG.IMG_SIZE, CFG.IMG_SIZE))
    img = tf.cast(img, tf.float32) / 255.0

    mask = tf.io.read_file(mask_path)
    mask = tf.image.decode_png(mask, channels=1)
    mask = tf.image.resize(mask, (CFG.IMG_SIZE, CFG.IMG_SIZE), method="nearest")
    mask = tf.cast(mask, tf.float32) / 255.0

    # Make sure mask is binary-ish
    mask = tf.where(mask > 0.5, 1.0, 0.0)

    return img, mask


def augment_image_and_mask(img, mask):
    # Horizontal flip
    if tf.random.uniform(()) > 0.5:
        img = tf.image.flip_left_right(img)
        mask = tf.image.flip_left_right(mask)

    # Brightness variation only on image
    img = tf.image.random_brightness(img, max_delta=0.15)
    img = tf.clip_by_value(img, 0.0, 1.0)

    # Random crop-like zoom: resize larger then random crop back
    if tf.random.uniform(()) > 0.5:
        bigger = CFG.IMG_SIZE + 32
        img = tf.image.resize(img, (bigger, bigger))
        mask = tf.image.resize(mask, (bigger, bigger), method="nearest")

        combined = tf.concat([img, mask], axis=-1)
        combined = tf.image.random_crop(combined, size=(CFG.IMG_SIZE, CFG.IMG_SIZE, 4))

        img = combined[:, :, :3]
        mask = combined[:, :, 3:]
        mask = tf.where(mask > 0.5, 1.0, 0.0)

    return img, mask


def make_dataset(pairs, training=False):
    img_paths = [p[0] for p in pairs]
    mask_paths = [p[1] for p in pairs]

    ds = tf.data.Dataset.from_tensor_slices((img_paths, mask_paths))
    ds = ds.map(load_image_and_mask, num_parallel_calls=tf.data.AUTOTUNE)

    if training:
        ds = ds.shuffle(buffer_size=len(pairs), seed=CFG.SEED)
        ds = ds.map(augment_image_and_mask, num_parallel_calls=tf.data.AUTOTUNE)

    ds = ds.batch(CFG.BATCH_SIZE)
    ds = ds.prefetch(tf.data.AUTOTUNE)
    return ds

train_ds = make_dataset(train_pairs, training=True)
val_ds = make_dataset(val_pairs, training=False)
test_ds = make_dataset(test_pairs, training=False)

print("Datasets ready.")

# 6. Fast visualization from original pairs

def show_one_raw_sample(pairs):
    img_path, mask_path = pairs[0]

    img = Image.open(img_path).convert("RGB")
    mask = Image.open(mask_path).convert("L")

    img = img.resize((CFG.IMG_SIZE, CFG.IMG_SIZE))
    mask = mask.resize((CFG.IMG_SIZE, CFG.IMG_SIZE))

    plt.figure(figsize=(8, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(img)
    plt.title("Input image")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(mask, cmap="gray")
    plt.title("Ground-truth mask")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

show_one_raw_sample(train_pairs)

# 7. Metrics and loss

SMOOTH = 1e-6

def dice_coef(y_true, y_pred):
    y_true_f = tf.reshape(y_true, [-1])
    y_pred_f = tf.reshape(y_pred, [-1])

    intersection = tf.reduce_sum(y_true_f * y_pred_f)
    return (2.0 * intersection + SMOOTH) / (
        tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f) + SMOOTH
    )

def dice_loss(y_true, y_pred):
    return 1.0 - dice_coef(y_true, y_pred)

def bce_dice_loss(y_true, y_pred):
    bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
    return bce + dice_loss(y_true, y_pred)

def iou_metric_tf(y_true, y_pred):
    y_pred = tf.cast(y_pred > 0.5, tf.float32)
    y_true = tf.cast(y_true > 0.5, tf.float32)

    intersection = tf.reduce_sum(y_true * y_pred)
    union = tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) - intersection

    return (intersection + SMOOTH) / (union + SMOOTH)

# 8. U-Net model from scratch

def conv_block(x, filters, dropout_rate=0.0):
    x = layers.Conv2D(filters, 3, padding="same", kernel_initializer="he_normal")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    x = layers.Conv2D(filters, 3, padding="same", kernel_initializer="he_normal")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation("relu")(x)

    if dropout_rate > 0:
        x = layers.Dropout(dropout_rate)(x)

    return x

def encoder_block(x, filters, dropout_rate=0.0):
    skip = conv_block(x, filters, dropout_rate)
    pooled = layers.MaxPooling2D((2, 2))(skip)
    return skip, pooled

def decoder_block(x, skip, filters, dropout_rate=0.0):
    x = layers.Conv2DTranspose(filters, 2, strides=2, padding="same")(x)
    x = layers.Concatenate()([x, skip])
    x = conv_block(x, filters, dropout_rate)
    return x

def build_unet(input_shape=(256, 256, 3), base_filters=32, dropout_rate=0.0):
    inputs = layers.Input(input_shape)

    s1, p1 = encoder_block(inputs, base_filters, dropout_rate)
    s2, p2 = encoder_block(p1, base_filters * 2, dropout_rate)
    s3, p3 = encoder_block(p2, base_filters * 4, dropout_rate)
    s4, p4 = encoder_block(p3, base_filters * 8, dropout_rate)

    bridge = conv_block(p4, base_filters * 16, dropout_rate)

    d1 = decoder_block(bridge, s4, base_filters * 8, dropout_rate)
    d2 = decoder_block(d1, s3, base_filters * 4, dropout_rate)
    d3 = decoder_block(d2, s2, base_filters * 2, dropout_rate)
    d4 = decoder_block(d3, s1, base_filters, dropout_rate)

    outputs = layers.Conv2D(1, 1, activation="sigmoid")(d4)

    return models.Model(inputs, outputs, name=f"UNet_base{base_filters}_dropout{dropout_rate}")

# 9. Training helper

def compile_model(model, learning_rate=1e-4):
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate),
        loss=bce_dice_loss,
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="accuracy"),
            tf.keras.metrics.Precision(name="precision"),
            tf.keras.metrics.Recall(name="recall"),
            dice_coef,
            iou_metric_tf,
        ],
    )
    return model


def get_callbacks(model_name):
    return [
        ModelCheckpoint(
            filepath=f"{CFG.MODEL_DIR}/{model_name}.keras",
            monitor="val_iou_metric_tf",
            mode="max",
            save_best_only=True,
            verbose=1,
        ),
        EarlyStopping(
            monitor="val_iou_metric_tf",
            mode="max",
            patience=4,
            restore_best_weights=True,
            verbose=1,
        ),
        ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.3,
            patience=2,
            min_lr=1e-6,
            verbose=1,
        ),
        CSVLogger(f"{CFG.LOG_DIR}/{model_name}_training_log.csv"),
    ]


def train_model(model, model_name):
    model = compile_model(model)
    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=CFG.EPOCHS,
        callbacks=get_callbacks(model_name),
    )
    return model, history

# 10. Experiment 1: Baseline model

baseline_model = build_unet(
    input_shape=(CFG.IMG_SIZE, CFG.IMG_SIZE, 3),
    base_filters=8,
    dropout_rate=0.0
)

baseline_model.summary()

baseline_model, baseline_history = train_model(
    baseline_model,
    model_name="baseline_unet"
)

# 11. Experiment 2: Improved model
# Improvement 1: more filters
# Improvement 2: dropout regularization
# Augmentation is already applied in the training dataset.

improved_model = build_unet(
    input_shape=(CFG.IMG_SIZE, CFG.IMG_SIZE, 3),
    base_filters=32,
    dropout_rate=0.05
)

improved_model.summary()

improved_model, improved_history = train_model(
    improved_model,
    model_name="improved_unet"
)

# 12. Plot training curves

def plot_history(history, title):
    hist = history.history

    plt.figure(figsize=(7, 4))
    plt.plot(hist["loss"], label="train_loss")
    plt.plot(hist["val_loss"], label="val_loss")
    plt.title(title + " - Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(7, 4))
    plt.plot(hist["iou_metric_tf"], label="train_iou")
    plt.plot(hist["val_iou_metric_tf"], label="val_iou")
    plt.title(title + " - IoU")
    plt.xlabel("Epoch")
    plt.ylabel("IoU")
    plt.legend()
    plt.grid(True)
    plt.show()

plot_history(baseline_history, "Baseline U-Net")
plot_history(improved_history, "Improved U-Net")

# 13. Final evaluation on TEST set
# This calculates IoU, Precision, Recall, F1, Dice, and average inference time.

def evaluate_segmentation_model(model, ds, threshold=0.5):
    all_true = []
    all_pred = []

    inference_times = []

    for imgs, masks in ds:
        start = time.time()
        preds = model.predict(imgs, verbose=0)
        end = time.time()

        batch_time = (end - start) / imgs.shape[0]
        inference_times.extend([batch_time] * imgs.shape[0])

        preds_binary = (preds > threshold).astype(np.uint8)
        masks_binary = (masks.numpy() > threshold).astype(np.uint8)

        all_true.append(masks_binary.reshape(-1))
        all_pred.append(preds_binary.reshape(-1))

    y_true = np.concatenate(all_true)
    y_pred = np.concatenate(all_pred)

    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    iou = jaccard_score(y_true, y_pred, zero_division=0)

    dice = (2 * precision * recall) / (precision + recall + 1e-6)
    avg_inference_time = float(np.mean(inference_times))

    return {
        "IoU": iou,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Dice": dice,
        "Avg inference time / image (sec)": avg_inference_time,
    }

baseline_results = evaluate_segmentation_model(baseline_model, test_ds)
improved_results = evaluate_segmentation_model(improved_model, test_ds)

results_df = pd.DataFrame([
    {"Model": "Baseline U-Net", **baseline_results},
    {"Model": "Improved U-Net", **improved_results},
])

results_df

# 14. Save experiment comparison table

results_path = "/content/sod_experiment_results.csv"
results_df.to_csv(results_path, index=False)
print("Saved:", results_path)
results_df

# 15. Visualization: original image, ground truth, prediction, and overlay

def show_predictions_with_overlay(model, ds, n=5, threshold=0.5):
    imgs, masks = next(iter(ds))
    preds = model.predict(imgs, verbose=0)

    n = min(n, imgs.shape[0])
    plt.figure(figsize=(16, 4 * n))

    for i in range(n):
        img = imgs[i].numpy()
        gt = masks[i].numpy().squeeze()
        pred = preds[i].squeeze()
        pred_bin = (pred > threshold).astype(np.float32)

        overlay = img.copy()
        # Highlight predicted foreground by increasing red channel
        overlay[:, :, 0] = np.maximum(overlay[:, :, 0], pred_bin)

        plt.subplot(n, 4, 4*i + 1)
        plt.imshow(img)
        plt.title("Input")
        plt.axis("off")

        plt.subplot(n, 4, 4*i + 2)
        plt.imshow(gt, cmap="gray")
        plt.title("Ground Truth")
        plt.axis("off")

        plt.subplot(n, 4, 4*i + 3)
        plt.imshow(pred_bin, cmap="gray")
        plt.title("Predicted Mask")
        plt.axis("off")

        plt.subplot(n, 4, 4*i + 4)
        plt.imshow(overlay)
        plt.title("Overlay")
        plt.axis("off")

    plt.tight_layout()
    plt.show()

show_predictions_with_overlay(improved_model, test_ds, n=5)

# 16. Single image demo function

def predict_single_image(model, image_path, threshold=0.5):
    original = Image.open(image_path).convert("RGB")
    resized = original.resize((CFG.IMG_SIZE, CFG.IMG_SIZE))

    img = np.array(resized).astype(np.float32) / 255.0
    img_batch = np.expand_dims(img, axis=0)

    start = time.time()
    pred = model.predict(img_batch, verbose=0)[0, :, :, 0]
    end = time.time()

    pred_bin = (pred > threshold).astype(np.float32)

    overlay = img.copy()
    overlay[:, :, 0] = np.maximum(overlay[:, :, 0], pred_bin)

    print(f"Inference time: {end - start:.4f} seconds")

    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.imshow(img)
    plt.title("Input Image")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(pred_bin, cmap="gray")
    plt.title("Predicted Mask")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(overlay)
    plt.title("Overlay")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

# Example:
# predict_single_image(improved_model, test_pairs[0][0])

# 17. Demo: upload one image and predict mask

from google.colab import files
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import time
import os

print("Click 'Choose Files' and upload one image for the demo.")

uploaded = files.upload()

if len(uploaded) == 0:
    print("No image uploaded.")
else:
    uploaded_filename = list(uploaded.keys())[0]
    print("Uploaded image:", uploaded_filename)

    # Use the improved model if it exists in memory.
    # If not, load the saved improved model from /content/models.
    if "improved_model" not in globals():
        print("Loading saved improved model...")
        improved_model = tf.keras.models.load_model(
            "/content/models/improved_unet.keras",
            custom_objects={
                "bce_dice_loss": bce_dice_loss,
                "dice_coef": dice_coef,
                "iou_metric_tf": iou_metric_tf
            }
        )

    original = Image.open(uploaded_filename).convert("RGB")
    resized = original.resize((CFG.IMG_SIZE, CFG.IMG_SIZE))

    img = np.array(resized).astype(np.float32) / 255.0
    img_batch = np.expand_dims(img, axis=0)

    start = time.time()
    pred = improved_model.predict(img_batch, verbose=0)[0, :, :, 0]
    end = time.time()

    pred_bin = (pred > 0.5).astype(np.float32)

    overlay = img.copy()
    overlay[:, :, 0] = np.maximum(overlay[:, :, 0], pred_bin)

    print(f"Inference time: {end - start:.4f} seconds")

    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.imshow(img)
    plt.title("Uploaded Image")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(pred_bin, cmap="gray")
    plt.title("Predicted Mask")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(overlay)
    plt.title("Overlay")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

